dist: xenial
os: linux

language: cpp
cache:
  directories:
    - experiments/mpich

before_install:
  - cd experiments
  - sh ./build_mpich.sh
  - cd ..

script:
  - cd experiments
  - ./setup.sh
  - cd ../build
  - ../experiments/mpich/bin/mpirun -np 1 ./lmp -in in.rhodo.dummy
  - ../experiments/mpich/bin/mpirun -np 1 ./lmp -in in.rhodo.dummy  -max-pi 11
  - ../experiments/mpich/bin/mpirun -np 1 ./lmp -in in.rhodo.dummy  -max-pi 0
  - ../experiments/mpich/bin/mpirun -np 1 ./lmp -in in.liquid-vapor -max-pi 5
  - ../experiments/mpich/bin/mpirun -np 1 ./lmp -in in.chain.scaled  -max-pi 1
  - ../experiments/mpich/bin/mpirun -np 1 ./lmp -in in.rhodo.scaled  -max-pi 1
